/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq_1.h"
#include "Fugt.h"
#include "Fugt_aliases.h"
#include "stromstyring_plus.h"
#include "stromstyring_plus_aliases.h"
#include "temperatur.h"
#include "temperatur_aliases.h"
#include "Niveau_vandtank.h"
#include "Niveau_vandtank_aliases.h"
#include "Pumpe.h"
#include "Pumpe_aliases.h"
#include "Lysfoler.h"
#include "Lysfoler_aliases.h"
#include "isr_EOC.h"
#include "Clock_1.h"
#include "Clock_out_capasitiv_sensors.h"
#include "Clock_out_capasitiv_sensors_aliases.h"
#include "UART.h"
#include "isr_UART.h"
#include "Rotor_motor1_plus_BLK.h"
#include "Rotor_motor1_plus_BLK_aliases.h"
#include "Rotor_motor2_plus_RED.h"
#include "Rotor_motor2_plus_RED_aliases.h"
#include "Rotor_motor1_minus_GRN.h"
#include "Rotor_motor1_minus_GRN_aliases.h"
#include "Rotor_motor2_minus_BLU.h"
#include "Rotor_motor2_minus_BLU_aliases.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "UART_IntClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

